### ISSUE TITLE
Image for building quarkus native executables

### ISSUE THREAD

**Issue by etsauer** [redhat-developer/devspaces-images#198]
I'm looking for a component image that can build a quarkus native application. The [quarkus sample workspace](https://github.com/crw-samples/quarkus-quickstarts/blob/devfilev2/devfile.yaml#L7-L53) that comes with CRW implies that you can package a native executable, but it references the `plugin-java11-rhel8` image to do it, which doesn't contain graalvm. I'm not seeing another image that does, so I'm happy to contribute one if there's interest.

**Comment by etsauer** [comment]
Alternatively, we could add graalvm to the java11 image

**Comment by nickboldt** [comment]
Are you still offering to publish a graalvm container image and associated sample project w/ a devfile v2.1 devfile? 

If so, please either open a [GH issue for Che](https://github.com/eclipse/che/issues/new/choose), or a [JIRA for Dev Spaces]((https://issues.jboss.org/secure/CreateIssue.jspa?pid=12321720&issuetype=1)
