### ISSUE TITLE
Fail to start a workspace with asynchronous storage

### ISSUE THREAD

**Issue by LiJunBJZhu** [redhat-developer/devspaces-images#209]
Server Version
2.15 @ f9f853 #6 :: Eclipse Che Dashboard 7.42.0 @ 74c0c

```
apiVersion: 1.0.0
metadata:
  name: python-ixwx
attributes:
  asyncPersist: 'true'
  persistVolumes: 'false'
projects:
  - name: python-hello-world
    source:
      location: 'https://devfile-registry-zlj-crw215.apps.amp-fb35.9.5.36.56.nip.io/resources/python-python-hello-world-master.zip'
      type: zip
components:
  - id: ms-python/python/latest
    preferences:
      python.globalModuleInstallation: true
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: venv
        containerPath: /home/jboss/.venv
    alias: python
    image: 'registry.redhat.io/codeready-workspaces/plugin-java8-rhel8@sha256:8cb1e495825051b83cf903bb317e55823a6f57b3bad92e9407dc8fa59c24c0cc'
commands:
  - name: 1. Run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/python-hello-world'
        type: exec
        command: python -m venv .venv && . .venv/bin/activate && python hello-world.py
        component: python
  - name: Debug current file
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "name": "Python: Current File",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "console": "internalConsole"
              }
            ]
          }
        type: vscode-launch
```

Add eth0 [10.131.0.63/23] from openshift-sdn

Pulling image "registry.redhat.io/codeready-workspaces/pluginbroker-metadata-rhel8@sha256:de8ede01ce5d3b06ae8b1866bb482bb937f020f7dee5dfb20b041f02c1e63f68"

Successfully pulled image "registry.redhat.io/codeready-workspaces/pluginbroker-metadata-rhel8@sha256:de8ede01ce5d3b06ae8b1866bb482bb937f020f7dee5dfb20b041f02c1e63f68" in 9.415142653s

Created container pluginbroker-metadata-rhel8-de8ede01ce

Started container pluginbroker-metadata-rhel8-de8ede01ce

Starting plugin metadata broker

Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'http://plugin-registry.zlj-crw215.svc:8080/v3/plugins/eclipse/che-async-pv-plugin/latest/meta.yaml': Downloading http://plugin-registry.zlj-crw215.svc:8080/v3/plugins/eclipse/che-async-pv-plugin/latest/meta.yaml failed. Status code 404. Response body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

<html><head>

<title>404 Not Found</title>

</head><body>

<h1>Not Found</h1>

<p>The requested URL was not found on this server.</p>

</body></html>

Failed to run the workspace: "Plugins installation process failed. Error: Plugin brokering process for workspace workspace91ds8zko8qf8pxu3 failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'http://plugin-registry.zlj-crw215.svc:8080/v3/plugins/eclipse/che-async-pv-plugin/latest/meta.yaml': Downloading http://plugin-registry.zlj-crw215.svc:8080/v3/plugins/eclipse/che-async-pv-plugin/latest/meta.yaml failed. Status code 404. Response body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL was not found on this server.</p> </body></html>

**Comment by nickboldt** [comment]
Closing, out of date. 2.15 is EOL. If you have problems with Dev Spaces 3.3, please open a JIRA: https://issues.jboss.org/secure/CreateIssue.jspa?pid=12321720&issuetype=1
