### ISSUE TITLE
Danger alert:Failed to fetch devfiles

### ISSUE THREAD

**Issue by kaovilai** [redhat-developer/devspaces-images#217]
After installing the operator, creating workspace instance, try to access route to workspace via kubeadmin and clicking trough sign ups

```
Failed to fetch devfiles metadata from registry URL: https://devfile-registry-openshift-workspaces.apps.cluster-<>/, reason: Network Error
```

**Comment by nickboldt** [comment]
was this a one-time error that went away a few seconds later when you refreshed the page? or a persistent issue? 

More info needed, please report a JIRA here: https://issues.jboss.org/secure/CreateIssue.jspa?pid=12321720&issuetype=1
