### ISSUE TITLE
Operator POD crashlooping on Openshift 4.10

### ISSUE THREAD

**Issue by gerbigma** [redhat-developer/devspaces-images#319]
Hi,
we installed Red Hat CodeReady Workspaces - Technical Preview
2.15.104+0.1661460923.p provided by Red Hat
on Openshift 4.10, but Operator Pod is crashlooping while running out of memory.
Seems memeory resource limit fix should be in:
https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-operator/deploy/deployment/openshift/combined.yaml
I'll try to change this :-)
<img width="516" alt="crw" src="https://user-images.githubusercontent.com/40384481/188821734-a05d9b46-10ab-48d1-a8e3-8a88a05fdef1.PNG">

**Comment by gerbigma** [comment]
#320

**Comment by nickboldt** [comment]
Is this still a concern after updating to 3.3? CRW 2.15 is EOL, while Dev Spaces 3.x replaces it and is actively being maintained.

**Comment by nickboldt** [comment]
If this is still an issue with 3.3 or newer, please open a new issue.
