### ISSUE TITLE
Provide Image with Openjdk 11 and Node 14

### ISSUE THREAD

**Issue by hupling** [redhat-developer/devspaces-images#59]
Can you please provide an image  Openjdk 11 and Node 14? An Image with OpenJDK 8 + Node 12 + Python 3 is already available.

**Comment by nickboldt** [comment]
Please report issues in our JIRA tracker.

I've migrated your issue to this one https://issues.redhat.com/browse/CRW-2598

Perhaps you'd prefer Node 16, now that it's available?

**Comment by nickboldt** [comment]
Closing, UDI image now has Node 16, OpenJDK 8/11/17, and Python 3.9
